name: Test

on:
  push:
    branches-ignore:
      - gh-readonly-queue/main/*

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Success
        run: |
          exit 0
