name: Test

# Some comment here
on:
  push:
    branches-ignore:
      - gh-readonly-queue/main/*
  merge_group:

concurrency:
  group: foobar
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Success
        run: |
          exit 0

  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Success
        run: |
          exit 0
