name: Test

# Some comment here
on:
  push:
    branches-ignore:
      - gh-readonly-queue/main/*
  merge_group:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Failure
        if: github.event_name == 'merge_group'
        run: |
          exit 1

      - name: Success
        if: github.event_name != 'merge_group'
        run: |
          exit 0

  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Success
        run: |
          exit 0
